---
  - name: Install unzip
    package:
      name: unzip
      update_cache: yes
    become: true

  - name: Download and install vault binary
    unarchive:
      src: "https://releases.hashicorp.com/vault/{{ vault_version }}/vault_{{ vault_version }}_linux_amd64.zip"
      dest: /usr/bin/
      remote_src: True
    become: true

  - name: Create vault config directory
    file: state=directory path=/etc/opt/vault/
    become: true

  - name: Copy vault config to server
    copy: src=vaultconfig.hcl dest=/etc/opt/vault/
    become: true

  - name: Copy vault service to server
    copy: src=vault.service dest=/usr/lib/systemd/system/vault.service
    become: true

  - name: Start vault service
    systemd:
      state: started
      name: vault
      daemon_reload: yes
    become: true

  - pause:
      seconds: 15

  - name: Initialize the vault
    command: vault operator init
    register: keys
    environment:
      VAULT_ADDR: "http://127.0.0.1:8200"

  - debug: msg="{{ keys }}"
